####
# ATENTION:
# Replace all occurences of lumen with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  lumen-mysql-data:
    driver: local

  # Redis Data
  lumen-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: lumen-mysql
    volumes:
      - lumen-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lumen
      - MYSQL_DATABASE=lumen
      - MYSQL_USER=lumen
      - MYSQL_PASSWORD=lumen

  # Redis
  cache:
    image: redis:4.0
    container_name: lumen-redis
    command: --appendonly yes
    volumes:
      - lumen-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: lumen-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  # queue:
  #   image: ambientum/php:7.2
  #   container_name: lumen-queue
  #   command: php artisan queue:listen
  #   volumes:
  #     - .:/var/www/app
  #   links:
  #     - mysql
  #     - cache